# Generated by Django 3.2.9 on 2021-12-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Agent Name')),
                ('description', models.TextField(verbose_name='Agent Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('image', models.ImageField(upload_to='img')),
            ],
            options={
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(verbose_name='Property ID')),
                ('location', models.CharField(max_length=60, verbose_name='Location')),
                ('property_type', models.CharField(choices=[('Apartments', 'Apartments'), ('Bungalow', 'Bungalow'), ('Presidental', 'Presidental')], max_length=60, verbose_name='Property Type')),
                ('status', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Open House', 'Open House')], max_length=10, verbose_name='Status')),
                ('area', models.IntegerField(verbose_name='Area')),
                ('beds', models.IntegerField(verbose_name='Beds')),
                ('baths', models.IntegerField(verbose_name='Baths')),
                ('garage', models.IntegerField(verbose_name='Garage')),
                ('property_description', models.TextField()),
                ('amenities', models.TextField()),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('image', models.ImageField(upload_to='img')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estateapp.agent', verbose_name='agent')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
