# Generated by Django 3.2.9 on 2021-12-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0005_auto_20211213_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agent',
            new_name='user',
        ),
        migrations.AddField(
            model_name='property',
            name='agent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estateapp.agent', verbose_name='agent'),
            preserve_default=False,
        ),
    ]
