# Generated by Django 3.2.9 on 2021-12-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0007_agtuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgtUser',
        ),
    ]
