# Generated by Django 3.2.9 on 2021-12-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0009_auto_20211214_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_title',
            field=models.CharField(default=1, max_length=60, verbose_name='Property Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
